env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - eslint-config-prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: latest
  sourceType: module
rules:
  '@typescript-eslint/ban-types': off
  '@typescript-eslint/strict-boolean-expressions': off
